WITH specialization_id AS (SELECT s.id
                           FROM specializations s
                           WHERE s.name = 'Программная инженерия и компьютерные науки')
INSERT
INTO subjects(name, semesters, specialization_id)
VALUES ('Алгебра и геометрия', 1, (SELECT id FROM specialization_id)),
       ('Алгоритмы и структуры данных', 1, (SELECT id FROM specialization_id)),
       ('Иностранный язык', 1, (SELECT id FROM specialization_id)),
       ('Информатика', 1, (SELECT id FROM specialization_id)),
       ('История', 1, (SELECT id FROM specialization_id)),
       ('Математическая логика и теория алгоритмов', 1, (SELECT id FROM specialization_id)),
       ('Математический анализ', 1, (SELECT id FROM specialization_id)),
       ('Программирование', 1, (SELECT id FROM specialization_id)),
       ('Алгебра и геометрия', 2, (SELECT id FROM specialization_id)),
       ('Алгоритмы и структуры данных', 2, (SELECT id FROM specialization_id)),
       ('Иностранный язык', 2, (SELECT id FROM specialization_id)),
       ('Математическая логика и теория алгоритмов', 2, (SELECT id FROM specialization_id)),
       ('Математический анализ', 2, (SELECT id FROM specialization_id)),
       ('Программирование', 2, (SELECT id FROM specialization_id)),
       ('Физика 1', 2, (SELECT id FROM specialization_id)),
       ('Цифровая схемотехника', 2, (SELECT id FROM specialization_id)),
       ('Дискретная математика', 3, (SELECT id FROM specialization_id)),
       ('Дополнительные главы математического анализа', 3, (SELECT id FROM specialization_id)),
       ('Иностранный язык', 3, (SELECT id FROM specialization_id)),
       ('Немецкий язык', 3, (SELECT id FROM specialization_id)),
       ('Логические основы программирования', 3, (SELECT id FROM specialization_id)),
       ('Основы объектно-ориентированного программирования', 3, (SELECT id FROM specialization_id)),
       ('Физика 2', 3, (SELECT id FROM specialization_id)),
       ('ЭВМ и периферийные устройства', 3, (SELECT id FROM specialization_id)),
       ('Деловой английский язык', 4, (SELECT id FROM specialization_id)),
       ('Дифференциальные уравнения и теория функций комплексного переменного', 4, (SELECT id FROM specialization_id)),
       ('Немецкий язык', 4, (SELECT id FROM specialization_id)),
       ('Объектно-ориентированное программирование на Java', 4, (SELECT id FROM specialization_id)),
       ('Операционные системы', 4, (SELECT id FROM specialization_id)),
       ('Основы параллельного программирования', 4, (SELECT id FROM specialization_id)),
       ('Основы риторики', 4, (SELECT id FROM specialization_id)),
       ('Принципы регистрации нейрофизиологических сигналов', 4, (SELECT id FROM specialization_id)),
       ('Сетевые технологии', 4, (SELECT id FROM specialization_id)),
       ('Теория вероятностей и математическая статистика', 4, (SELECT id FROM specialization_id)),
       ('Физика 2', 4, (SELECT id FROM specialization_id)),
       ('Философия', 4, (SELECT id FROM specialization_id)),
       ('Английский язык', 5, (SELECT id FROM specialization_id)),
       ('Базы данных', 5, (SELECT id FROM specialization_id)),
       ('Вычислительная математика', 5, (SELECT id FROM specialization_id)),
       ('Допустимые множества и вычислимость', 5, (SELECT id FROM specialization_id)),
       ('Когнитивная психология', 5, (SELECT id FROM specialization_id)),
       ('Методы трансляции и компиляции', 5, (SELECT id FROM specialization_id)),
       ('Объектно-ориентированный анализ и дизайн', 5, (SELECT id FROM specialization_id)),
       ('Операционные системы', 5, (SELECT id FROM specialization_id)),
       ('Практическая информационная безопасность', 5, (SELECT id FROM specialization_id)),
       ('Сети и телекоммуникации', 5, (SELECT id FROM specialization_id)),
       ('Электротехника и электроника', 5, (SELECT id FROM specialization_id)),
       ('Английский язык', 6, (SELECT id FROM specialization_id)),
       ('Архитектура современных микропроцессоров и мультипроцессоров', 6, (SELECT id FROM specialization_id)),
       ('Базы данных', 6, (SELECT id FROM specialization_id)),
       ('Биоинформатика', 6, (SELECT id FROM specialization_id)),
       ('Введение в ГИС-технологии', 6, (SELECT id FROM specialization_id)),
       ('Введение в теорию кодирования', 6, (SELECT id FROM specialization_id)),
       ('Допустимые множества и вычислимость', 6, (SELECT id FROM specialization_id)),
       ('Измерительный практикум', 6, (SELECT id FROM specialization_id)),
       ('Инженерная и компьютерная графика', 6, (SELECT id FROM specialization_id)),
       ('Информационные технологии в Интернет-маркетинге', 6, (SELECT id FROM specialization_id)),
       ('Компьютерное моделирование в науках о Земле', 6, (SELECT id FROM specialization_id)),
       ('Логические методы в инженерии знаний', 6, (SELECT id FROM specialization_id)),
       ('Методы визуализации информации при помощи графов', 6, (SELECT id FROM specialization_id)),
       ('Модели и методы искусственного интеллекта', 6, (SELECT id FROM specialization_id)),
       ('Основы бизнес-моделирования в системе Business Studio', 6, (SELECT id FROM specialization_id)),
       ('Основы теории управления', 6, (SELECT id FROM specialization_id)),
       ('Правоведение', 6, (SELECT id FROM specialization_id)),
       ('Практическая информационная безопасность', 6, (SELECT id FROM specialization_id)),
       ('Программируемые микроконтроллеры', 6, (SELECT id FROM specialization_id)),
       ('Психология в информационных технологиях', 6, (SELECT id FROM specialization_id)),
       ('Разработка систем компьютерного зрения', 6, (SELECT id FROM specialization_id)),
       ('Современные методы глубокого машинного обучения', 6, (SELECT id FROM specialization_id)),
       ('Теория автоматов', 6, (SELECT id FROM specialization_id)),
       ('Теория и практика нейронных сетей', 6, (SELECT id FROM specialization_id)),
       ('Управление производственным процессом разработки программного обеспечения', 6, (SELECT id FROM specialization_id)),
       ('Цифровая обработка сигналов', 6, (SELECT id FROM specialization_id)),
       ('Эффективное программирование современных микропроцессоров и мультипроцессоров', 6, (SELECT id FROM specialization_id)),
       ('Безопасность в IoT (Интернет вещей)', 7, (SELECT id FROM specialization_id)),
       ('Введение в C# и платформу .NET', 7, (SELECT id FROM specialization_id)),
       ('Введение в разработку мобильных приложений', 7, (SELECT id FROM specialization_id)),
       ('Защита информации', 7, (SELECT id FROM specialization_id)),
       ('Инжиниринг современных информационных систем', 7, (SELECT id FROM specialization_id)),
       ('Инновационная экономика и технологическое предпринимательство', 7, (SELECT id FROM specialization_id)),
       ('Информационный поиск', 7, (SELECT id FROM specialization_id)),
       ('Интеллектуальный анализ данных', 7, (SELECT id FROM specialization_id)),
       ('Коллективная разработка программного обеспечения', 7, (SELECT id FROM specialization_id)),
       ('Криптография для информационных технологий', 7, (SELECT id FROM specialization_id)),
       ('Моделирование', 7, (SELECT id FROM specialization_id)),
       ('Оптимизация производительности Java-программ', 7, (SELECT id FROM specialization_id)),
       ('Парадигмы программирования', 7, (SELECT id FROM specialization_id)),
       ('Прикладные алгоритмы обработки цифровых изображений', 7, (SELECT id FROM specialization_id)),
       ('Программирование встраиваемых систем', 7, (SELECT id FROM specialization_id)),
       ('Программирование на языке Python', 7, (SELECT id FROM specialization_id)),
       ('Программируемые системы визуализации', 7, (SELECT id FROM specialization_id)),
       ('Разработка мобильных приложений на платформе Android', 7, (SELECT id FROM specialization_id)),
       ('Стандартизация программной документации', 7, (SELECT id FROM specialization_id)),
       ('Языки и методы программирования информационно-управляющих систем', 7, (SELECT id FROM specialization_id)),
       ('Языки и системы искусственного интеллекта', 7, (SELECT id FROM specialization_id)),
       ('Безопасность жизнедеятельности', 8, (SELECT id FROM specialization_id)),
       ('Введение в организацию распределенных вычислений', 8, (SELECT id FROM specialization_id)),
       ('Особенности коммерческой разработки программного обеспечения', 8, (SELECT id FROM specialization_id)),
       ('Построение сервис-ориентированной архитектуры приложений', 8, (SELECT id FROM specialization_id)),
       ('Распределенные алгоритмы', 8, (SELECT id FROM specialization_id)),
       ('Распределенные информационные системы', 8, (SELECT id FROM specialization_id)),
       ('Экономика', 8, (SELECT id FROM specialization_id))